In [1]:
import numpy as np
import pandas as pd

In [2]:
train_path = "../data/hepmass/1000_train.csv"
names = ['label']+[i for i in range(27)]
train_data = pd.read_csv(train_path, header=0, names=names)
train_data.head()

,label,0,1,2,3,4,5,6,7,8,...,17,18,19,20,21,22,23,24,25,26
0,1.0,0.217896,0.933072,-0.596174,1.148478,-1.054270,0.850488,1.660115,-1.315179,0.645059,...,1.226331,2.104148,-1.281571,-0.379576,-0.573682,1.539113,1.567046,0.505360,-0.555226,2.961334
1,1.0,1.569236,1.686193,-0.222665,0.485782,-0.544683,-1.054221,0.059797,-0.015302,1.363171,...,1.226331,-0.371889,0.092913,0.817892,-0.573682,0.407313,0.334834,-0.247829,-0.758830,0.563377
2,0.0,-0.360693,1.794174,0.264738,-0.472273,-0.292344,-1.054221,-1.150495,1.423404,1.270098,...,1.226331,-1.199511,0.539020,-1.590629,-0.573682,-0.543636,-0.937456,-0.300344,-0.523262,-1.506304
3,1.0,-0.691130,-1.063802,-1.198263,0.691331,-1.083016,-1.054221,0.769120,-0.280765,-1.228812,...,1.226331,-0.719277,0.741245,0.480195,-0.573682,1.698463,2.433028,-0.239303,0.967155,0.336279
4,0.0,-0.067436,-0.636762,-0.620166,-0.062551,1.588715,-0.005984,-0.595304,-1.238987,0.336844,...,-0.815440,-0.552837,-1.418494,-0.562982,1.743123,0.881802,0.002516,1.560950,-0.150760,-1.023889

In [3]:
test_path = "../data/hepmass/1000_test.csv"
names = ['label']+[i for i in range(27)]
test_data = pd.read_csv(test_path, header=0, names=names)
test_data.head()

,label,0,1,2,3,4,5,6,7,8,...,17,18,19,20,21,22,23,24,25,26
0,0.0,0.094394,0.012756,0.911933,-0.090831,-0.233575,-1.054221,-0.975937,-1.067278,-0.613850,...,-0.815440,-1.376865,0.067591,1.372576,-0.573682,-1.368692,-0.479379,1.529256,-0.575782,-1.290232
1,1.0,0.979433,0.582031,1.425125,1.149996,-1.619561,-0.005984,0.815265,-1.175631,0.094345,...,1.226331,-0.192464,0.009078,0.605600,-0.573682,-0.752050,-1.033962,1.628678,2.058113,0.718816
2,1.0,1.076495,0.965307,1.016853,1.187370,0.787062,0.850488,0.562133,0.446859,-1.129008,...,1.226331,-0.018303,-0.007021,0.710188,-0.573682,0.334767,-0.380174,-0.355861,1.384390,0.388062
3,0.0,-1.186220,0.443335,0.003997,0.484752,-1.159905,-1.054221,-1.581964,-0.391629,0.529644,...,1.226331,-0.520804,-1.241476,-0.137923,-0.573682,-0.254372,-0.253829,0.333148,-0.554347,-0.905452
4,1.0,1.124759,-1.123493,-1.104635,1.144637,-0.903607,-0.005984,0.602021,-0.321545,0.838113,...,-0.815440,1.045574,-1.235976,-0.500231,1.743123,-0.039101,-0.319992,-0.395673,0.891474,0.327889

In [4]:
test_data = test_data.to_numpy()
train_data = train_data.to_numpy()

X_test = test_data[:, 1:]
y_test = test_data[:, 0].astype(np.int64)
X_train = train_data[:, 1:]
y_train = train_data[:, 0].astype(np.int64)

In [5]:
X_train.shape, X_test.shape

((7000000, 27), (3500000, 27))

In [6]:
data_path = '../data/hepmass'
np.save( f'{data_path}/X_train', X_train)
np.save( f'{data_path}/X_test', X_test)
np.save( f'{data_path}/y_train', y_train)
np.save( f'{data_path}/y_test', y_test)

In [ ]:
from sklearn.metrics import accuracy_score as acc
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=200, metric='cosine')
knn.fit(X_train.reshape(X_train.shape[0],-1), y_train)
accuracy = knn.score(X_test.reshape(X_test.shape[0],-1), y_test)
accuracy

In [1]:
import numpy as np
data_path = '../data/hepmass'
X_train=np.load( f'{data_path}/X_train.npy')
X_test=np.load( f'{data_path}/X_test.npy')
y_train=np.load( f'{data_path}/y_train.npy')
y_test=np.load( f'{data_path}/y_test.npy')

In [2]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
acc = []
for rand_seed in [0,1,2,3,4]:
    np.random.seed(rand_seed)
    lr = LogisticRegression(max_iter=300, random_state=rand_seed)
    lr.fit(X_train,y_train)
    predicted_labels = lr.predict(X_test)
    acc.append(metrics.accuracy_score(y_test, predicted_labels))
acc = np.stack(acc)
print(acc.mean(), acc.std())

0.9069362857142858 0.0